
name: CD Fake
on: 
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
        # inputs:
        #     AMBIENTE_DEPLOY:
        #         type: choice
        #         options:
        #             - homologacao
        #             - producao 
jobs:
    build-aplicacao: 
        runs-on: ubuntu-latest
        environment:
            name: homologacao
            url: https://homologacao.fake.com 
        steps:
            - name: Build da aplicacao
              run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"

    teste-and-quality: 
        runs-on: ubuntu-latest
        environment: 
            name: homologacao
            url: https://homologacao.fake.com 
        needs: [build-aplicacao]
        steps:
            - name: Realizado testes
              run: echo "Teste no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"

    cd-producao-fake: 
        needs: [teste-and-quality]
        uses: casoftsolutions/gerenciando-ambiente/.github/workflows/main.yml@main
        with:
            ambiente: producao
            url: https://producao.fake.com



#desafio: criar um  cd.producao.yaml para o ambiente de producao e passar  como parametro o ambiente de deploy             