
name: CD Fake
on: 
    push:
        branches:
            - main
            - develop
jobs:
    deploy-fake:
        runs-on: ubuntu-latest
        environment: homologacao
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"