
name: CD Fake
on: 
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
        inputs:
            AMBIENTE_DEPLOY:
                type: choice
                options:
                    - homologacao
                    - producao 
jobs:
    deploy-fake:
        runs-on: ubuntu-latest
        environment: homologacao
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"